// src/accountweb-usercenter-vue/src/components/Header.vue
<template>
    <header class="header-container">
        <nav>
            <ul class="visible-xs visible-sm">
                <li><a id="sidebar-toggler" href="#" class="menu-link menu-link-slide"><span><em></em></span></a></li>
            </ul>
            <ul class="hidden-xs">
                <li><a id="offcanvas-toggler" href="#" class="menu-link menu-link-slide"><span><em></em></span></a></li>
            </ul>
            <h2 class="header-title">Dashboard</h2>
            <ul class="pull-right">
                <li><a id="header-search" href="#" class="ripple"><em class="ion-ios-search-strong"></em></a></li>
                <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle has-badge ripple"><em class="ion-person"></em><sup class="badge bg-danger">3</sup></a>
                    <ul class="dropdown-menu dropdown-menu-right md-dropdown-menu">
                        <li><a href="profile.html"><em class="ion-home icon-fw"></em>Profile</a></li>
                        <li><a href="messages.html"><em class="ion-gear-a icon-fw"></em>Messages</a></li>
                        <li role="presentation" class="divider"></li>
                        <li><a href="user.login.html"><em class="ion-log-out icon-fw"></em>Logout</a></li>
                    </ul>
                </li>
                <li><a id="header-settings" href="#" class="ripple"><em class="ion-gear-b"></em></a></li>
            </ul>
        </nav>
    </header>
</template>

<script>
    export default {
        data() {
            return {
                msg: 'Welcome to Your Vue.js App'
            }
        }
    }

</script>

// src/accountweb/ng2centric/src/app/layout/header/header.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { ModalDirective } from 'ng2-bootstrap';

import { SettingsService } from '../../shared/settings/settings.service';
import { PagetitleService } from '../../core/pagetitle/pagetitle.service';

@Component({
    selector: 'app-header',
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.scss', './header.menu-links.scss'],
    encapsulation: ViewEncapsulation.None
})
export class HeaderComponent implements OnInit {

    sidebarVisible: true;
    sidebarOffcanvasVisible: boolean;

    constructor(private settings: SettingsService, private pt: PagetitleService) { }


    ngOnInit() {
    }

    toggleSidebarOffcanvasVisible() {
        this.settings.app.sidebar.offcanvasVisible = !this.settings.app.sidebar.offcanvasVisible;
    }

    toggleSidebar(state) {
        //  state === true -> open
        //  state === false -> close
        //  state === undefined -> toggle
        this.settings.app.sidebar.visible = typeof state !== 'undefined' ? state : !this.settings.app.sidebar.visible;
    }

    openModalSearch() {

    }

    openModalBar() {

    }

}

<div class="header-container">
    <nav>
        <ul>
            <li [ngClass]="{'active': settings.app.sidebar.visible}" class="visible-xs visible-sm hidden-md">
                <a (click)="toggleSidebar()" [ngClass]="settings.app.header.menulink" class="menu-link">
                    <span><em></em></span>
                </a>
            </li>
            <li [ngClass]="{'active': settings.app.sidebar.offcanvasVisible}" *ngIf="settings.app.sidebar.offcanvas" class="hidden-xs hidden-sm">
                <a (click)="toggleSidebarOffcanvasVisible()" [ngClass]="settings.app.header.menulink" class="menu-link">
                    <span><em></em></span>
                </a>
            </li>
        </ul>
        <h2 [innerHTML]="pt.getTitle()" class="header-title"></h2>
        <ul class="pull-right">
            <li>
                <a (click)="headerSearch.searchModal.show()" class="ripple">
                    <em class="ion-ios-search-strong"></em>
                </a>
            </li>
            <li dropdown class="dropdown">
                <a dropdownToggle class="dropdown-toggle has-badge ripple">
                    <em class="ion-person"></em>
                    <sup class="badge bg-danger">3</sup>
                </a>
                <ul dropdownMenu class="dropdown-menu dropdown-menu-right md-dropdown-menu">
                    <li class="ripple ripple-block">
                        <a><em class="ion-home icon-fw"></em>Profile</a>
                    </li>
                    <li class="ripple ripple-block">
                        <a><em class="ion-gear-a icon-fw"></em>Settings</a>
                    </li>
                    <li role="presentation" class="divider"></li>
                    <li class="ripple ripple-block">
                        <a><em class="ion-log-out icon-fw"></em>Logout</a>
                    </li>
                </ul>
            </li>
            <li><a (click)="seetingsBar.settingsModal.show()" class="ripple"><em class="ion-gear-b"></em></a></li>
        </ul>
    </nav>
</div>
<header-search #headerSearch></header-search>
<app-settings #seetingsBar></app-settings>
